import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const fontMulish = localFont({
  src: "./fonts/Mulish.ttf",
  variable: "--font-mulish",
});

const fontKharkiv = localFont({
  src: "./fonts/Kharkiv.ttf",
  variable: "--font-kharkiv",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontMulish.variable} ${fontKharkiv.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
